version: "2"
services:
 web:
  container_name: gentregas-api
  image: engweb2024/gentregas
  ports:
    - "2804:2204"
  depends_on:
    - mongo
  links:
    - mongo
 mongo:
  container_name: mongo-server
  image: mongo
